name: Check for print/console.log statements

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  lint-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Scan for print() and console.log()
        run: |
          set -e
          echo "Scanning submodules..."
          for dir in $(find . -type f \( -name '*.js' -o -name '*.ts' -o -name '*.py' \)); do
            if grep -nE '^\s*\bprint\s*\(|console\.log\s*\(' "$dir" | grep -v 'Blueprint'; then
              echo "Debug statements found!"
              exit 1
            fi
          done
